# Generated by Django 3.0.7 on 2020-07-05 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobs', models.TextField(max_length=100)),
                ('image', models.ImageField(upload_to=None)),
                ('job_description', models.TextField(max_length=500, verbose_name='Job Description')),
                ('startDate', models.DateField(verbose_name='Start Date')),
                ('End_Date', models.DateField(verbose_name='End Date')),
                ('employer', models.TextField(max_length=100)),
                ('contact_info', models.EmailField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Semester', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassName', models.CharField(max_length=20, verbose_name='Class Name')),
                ('Description', models.TextField(max_length=50)),
                ('Professor', models.TextField(max_length=30, null=True)),
                ('Grade', models.CharField(max_length=5)),
                ('Projects', models.CharField(max_length=100, null=True)),
                ('Semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.Semester')),
            ],
        ),
    ]
