# Generated by Django 3.0.7 on 2020-07-06 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_auto_20200705_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField(max_length=500)),
                ('startDate', models.DateField(verbose_name='Start Date')),
                ('End_Date', models.DateField(verbose_name='End Date')),
                ('Mentor', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=30)),
            ],
        ),
    ]
