# Generated by Django 3.0.7 on 2020-07-08 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_certifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certifications',
            name='Cert_Image',
        ),
    ]
