# Generated by Django 3.0.7 on 2020-07-08 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_remove_certifications_cert_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='certifications',
            name='Status',
            field=models.CharField(choices=[('IP', 'In Progress'), ('CO', 'Completed')], default='IP', max_length=11),
            preserve_default=False,
        ),
    ]
