# Generated by Django 3.0.7 on 2020-07-08 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0007_certifications_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='certifications',
            name='year',
            field=models.CharField(default='CO', max_length=4),
            preserve_default=False,
        ),
    ]
