# Generated by Django 3.0.7 on 2020-07-08 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0008_certifications_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certifications',
            name='Status',
            field=models.CharField(choices=[('In Progress', 'IP'), ('Completed', 'CO')], max_length=11),
        ),
    ]
