# Generated by Django 3.0.7 on 2020-07-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0009_auto_20200708_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certifications',
            name='Status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=11),
        ),
    ]
